services:
  homework8.mobile.rabbitmq.rabbitmq:
    image: rabbitmq:3-management
    container_name: homework8_mobile_rabbitmq_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/
        

volumes: 
  rabbitmq_data: